### ISSUE TITLE
Input Image

### ISSUE THREAD

**Issue by Jojopok** [WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Blog#62]
La case pour inscrire une image ne fonctionne pas, rien ne s'affiche pas 
![image](https://github.com/WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Blog/assets/116583040/a245a9b0-5b5f-4d5a-9bff-17eb2c36de35)

**Comment by JulieRaymond** [comment]
normal elle doit partir, les images sont à insérer directement via une URL dans l'outil Ckeditor :)
