### ISSUE TITLE
Ajout d'une catégorie

### ISSUE THREAD

**Issue by Jojopok** [WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Blog#63]
Quand on édite et qu'on ajoute une catégorie, il faut rééditer une nouvelle fois pour avoir le choix d'ajouter en plus la nouvelle catégorie, sinon cela remplace toutes les autres.

![image](https://github.com/WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Blog/assets/116583040/d24edc02-d748-4b22-91e7-3f149d5156f2)

**Comment by JulieRaymond** [comment]
oui on sait 😭😭😭😭 ça fait partie des axes d'améliorations ahhaha
