### ISSUE TITLE
Image trop grosse

### ISSUE THREAD

**Issue by Jojopok** [WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Blog#67]
Si on ajoute une image trop grosse elle prend trop d'espace sur la page

![image](https://github.com/WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Blog/assets/116583040/f7628325-9e59-4383-af89-f0ba651dc834)

**Comment by JulieRaymond** [comment]
L'utilisateur est libre de créer dans CKEDITOR la taille d'image de son choix, pour sa propre page de profil, c'est donc de sa responsabilité mdr hahahahhahah
