### ISSUE TITLE
impossible de se connecter

### ISSUE THREAD

**Issue by yoyodes1000** [WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Blog#71]
on me dit que la photo est obligatoire

**Comment by JulieRaymond** [comment]
Oui ahhaha c'est pensé comme ça !

**Comment by JulieRaymond** [comment]
https://github.com/WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Blog/assets/122172605/54c09c5e-ceea-4c52-9b6c-c7f74cc95189
