### ISSUE TITLE
Button "confirmer la suppression" throws an error

### ISSUE THREAD

**Issue by msmithfc300** [WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Blog#73]
I tried to delete an article and when I selected the button "confirmer la suppression" I got this error: PDOException thrown with message "SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`bdd_blog`.`article_category`, CONSTRAINT `article_category_ibfk_1` FOREIGN KEY (`article_id`) REFERENCES `article` (`id`))"

Stacktrace:
#4 PDOException in /Users/Martha/Documents/2023-09-PHP-Bordeaux-P2-Blog/src/Model/ArticleManager.php:43
#3 PDOStatement:execute in /Users/Martha/Documents/2023-09-PHP-Bordeaux-P2-Blog/src/Model/ArticleManager.php:43
#2 App\Model\ArticleManager:deleteArticle in /Users/Martha/Documents/2023-09-PHP-Bordeaux-P2-Blog/src/Controller/ArticleController.php:202
#1 App\Controller\ArticleController:deleteArticleById in /Users/Martha/Documents/2023-09-PHP-Bordeaux-P2-Blog/src/routing.php:37
#0 require_once in /Users/Martha/Documents/2023-09-PHP-Bordeaux-P2-Blog/public/index.php:11

**Comment by JulieRaymond** [comment]
Moi la suppression fonctionne pourtant très bien je viens de retester :)

**Comment by JulieRaymond** [comment]
https://github.com/WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Blog/assets/122172605/efbcd40b-ae39-436e-bf44-e879f0e9357a

**Comment by Jojopok** [comment]
J'ai le même soucis : 
![image](https://github.com/WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Blog/assets/116583040/cff09ae4-3dd4-416c-8771-117decb6d106)

**Comment by JulieRaymond** [comment]
j'ai réglé merci à vous :)
